CREATE TABLE IF NOT EXISTS ghl_api_keys (
  id INT PRIMARY KEY AUTO_INCREMENT,
  sub_account_id VARCHAR(255) UNIQUE NOT NULL,
  api_key TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);